# set this variable to the director in which you saved the common files
commondir = ../common/

all : lab1-1

lab1-1 : lab1-1.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c
	g++ -Wall -o lab1-1 -I$(commondir) -I../common/Windows -DGL_GLEXT_PROTOTYPES lab1-1.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c -lopengl32 -lglu32 -lgdi32

lab1-2 : lab1-2.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c
	g++ -Wall -o lab1-2 -I$(commondir) -I../common/Windows -DGL_GLEXT_PROTOTYPES lab1-2.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c -lopengl32 -lglu32 -lgdi32

lab1-3 : lab1-3.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c
	g++ -Wall -o lab1-3 -I$(commondir) -I../common/Windows -DGL_GLEXT_PROTOTYPES lab1-3.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c -lopengl32 -lglu32 -lgdi32

lab1-4 : lab1-4.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c
	g++ -Wall -o lab1-4 -I$(commondir) -I../common/Windows -DGL_GLEXT_PROTOTYPES lab1-4.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c -lopengl32 -lglu32 -lgdi32

lab1-5 : lab1-5.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c
	g++ -Wall -o lab1-5 -I$(commondir) -I../common/Windows -DGL_GLEXT_PROTOTYPES lab1-5.cpp $(commondir)GL_utilities.c $(commondir)LoadTGA.c $(commondir)Windows/MicroGlut.c $(commondir)Windows/glew.c -lopengl32 -lglu32 -lgdi32


clean :
	rm lab1-1
